/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package empresa;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Lucas
 */
public class InterfaceGrafica extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGrafica
     */
    public InterfaceGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        novoButton = new javax.swing.JMenuItem();
        abrirButton = new javax.swing.JMenuItem();
        salvarButton = new javax.swing.JMenuItem();
        fecharButton = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        sairButton = new javax.swing.JMenuItem();
        EmpresaButton = new javax.swing.JMenu();
        NewEmpresa = new javax.swing.JMenuItem();
        EditEmpresa = new javax.swing.JMenuItem();
        empresaListar = new javax.swing.JMenuItem();
        SetorButton = new javax.swing.JMenu();
        newSetor = new javax.swing.JCheckBoxMenuItem();
        ColaboradoresButton = new javax.swing.JMenu();
        newFuncionario = new javax.swing.JCheckBoxMenuItem();
        newCliente = new javax.swing.JCheckBoxMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Empresas");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("          BEM VINDO AO GERENCIADOR DE    ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("EMPRESAS FUNCIONARIOS E CLIENTES");

        jMenu1.setText("Arquivo");

        novoButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        novoButton.setText("Novo");
        novoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoButtonActionPerformed(evt);
            }
        });
        jMenu1.add(novoButton);

        abrirButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        abrirButton.setText("Abrir");
        abrirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirButtonActionPerformed(evt);
            }
        });
        jMenu1.add(abrirButton);

        salvarButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        salvarButton.setText("Salvar");
        salvarButton.setEnabled(false);
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });
        jMenu1.add(salvarButton);

        fecharButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        fecharButton.setText("Fechar");
        fecharButton.setEnabled(false);
        fecharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharButtonActionPerformed(evt);
            }
        });
        jMenu1.add(fecharButton);
        jMenu1.add(jSeparator1);

        sairButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        jMenu1.add(sairButton);

        jMenuBar1.add(jMenu1);

        EmpresaButton.setText("Empresa");
        EmpresaButton.setEnabled(false);
        EmpresaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpresaButtonActionPerformed(evt);
            }
        });

        NewEmpresa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        NewEmpresa.setText("Novo");
        NewEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewEmpresaActionPerformed(evt);
            }
        });
        EmpresaButton.add(NewEmpresa);

        EditEmpresa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        EditEmpresa.setText("Editar");
        EditEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditEmpresaActionPerformed(evt);
            }
        });
        EmpresaButton.add(EditEmpresa);
        EditEmpresa.setEnabled(false);

        empresaListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        empresaListar.setText("Lista empresas");
        empresaListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaListarActionPerformed(evt);
            }
        });
        EmpresaButton.add(empresaListar);

        jMenuBar1.add(EmpresaButton);

        SetorButton.setText("Setor");
        SetorButton.setEnabled(false);

        newSetor.setText("Novo");
        newSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSetorActionPerformed(evt);
            }
        });
        SetorButton.add(newSetor);
        newSetor.setEnabled(false);

        jMenuBar1.add(SetorButton);

        ColaboradoresButton.setText("Colaboradores");
        ColaboradoresButton.setEnabled(false);

        newFuncionario.setText("Novo Funcionario");
        newFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFuncionarioActionPerformed(evt);
            }
        });
        ColaboradoresButton.add(newFuncionario);
        newFuncionario.setEnabled(false);

        newCliente.setText("Novo Cliente");
        newCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newClienteActionPerformed(evt);
            }
        });
        ColaboradoresButton.add(newCliente);
        newCliente.setEnabled(false);

        jMenuBar1.add(ColaboradoresButton);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ArquivoNovoEnable(){
        boolean arquivo = arquivoAtual != null;
        EmpresaButton.setEnabled(true);
        fecharButton.setEnabled(true);
        abrirButton.setEnabled(true);
        newCliente.setEnabled(true);
        newSetor.setEnabled(true);
        newFuncionario.setEnabled(true);
        if (!arquivo) {
            this.setTitle("Gerenciador de Empresas");
        } else {
            this.setTitle("Gerenciador de Empresas {" + arquivoAtual.getName() + "}");

        }
    }
    
    private void EmpresaNovaEnable(){//sujeito a alteração
       EditEmpresa.setEnabled(true);
       newFuncionario.setEnabled(true);
       newSetor.setEnabled(true);
       newCliente.setEnabled(true);
       salvarButton.setEnabled(true);
       SetorButton.setEnabled(true);
       ColaboradoresButton.setEnabled(true);
       
    }
    private void ArquivoFecharEnable(){
        EmpresaButton.setEnabled(false);
        SetorButton.setEnabled(false);
        ColaboradoresButton.setEnabled(false);
        fecharButton.setEnabled(false);
        abrirButton.setEnabled(true);
        salvarButton.setEnabled(false);

    }
    
    private void EditEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditEmpresaActionPerformed
        // TODO add your handling code here:
            NovaEmpresaInterface dialog = new NovaEmpresaInterface(new javax.swing.JFrame(), true);
            
            dialog.setModel(empresaAtual);
            dialog.pack();
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
            
            Empresa retorno = dialog.getModalResult();
            if(retorno != null){
               empresaAtual = retorno;
            }
            
            
        
    }//GEN-LAST:event_EditEmpresaActionPerformed

    private void EmpresaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpresaButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_EmpresaButtonActionPerformed

    private void NewEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewEmpresaActionPerformed
        // TODO add your handling code here:
       NovaEmpresaInterface dialog = new NovaEmpresaInterface(new javax.swing.JFrame(), true);
       dialog.pack();
       dialog.setLocationRelativeTo(null);
       dialog.setVisible(true);
       Empresa retorno = dialog.getModalResult();
       if(retorno!=null){
           empresaAtual=retorno;
           empresaLista.add(retorno);
           EmpresaNovaEnable();
       }
       
       
    }//GEN-LAST:event_NewEmpresaActionPerformed

    private void empresaListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaListarActionPerformed
        // TODO add your handling code here:
        EmpresaLista dialog = new EmpresaLista(this, true);
        dialog.setModel(empresaLista);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        
    }//GEN-LAST:event_empresaListarActionPerformed

    private void newSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSetorActionPerformed
        // TODO add your handling code here:
       NovoSetor dialog = new NovoSetor(this,true); 
       dialog.pack();
       dialog.setLocationRelativeTo(null);
       dialog.setVisible(true);
       
    }//GEN-LAST:event_newSetorActionPerformed

    private void newFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFuncionarioActionPerformed
        // TODO add your handling code here:
        NovoFuncionario dialog = new NovoFuncionario(this,true);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        
    }//GEN-LAST:event_newFuncionarioActionPerformed

    private void newClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newClienteActionPerformed

    private void novoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            arquivoAtual = fileChooser.getSelectedFile();
            ArquivoNovoEnable();
        }
        
    }//GEN-LAST:event_novoButtonActionPerformed

    private void fecharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharButtonActionPerformed
        // TODO add your handling code here:
        int resposta = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja fechar? Arquivos não salvos seram perdidos.", "Fechar", JOptionPane.OK_CANCEL_OPTION);
        if(resposta==0){
            ArquivoFecharEnable();
            arquivoAtual=null;
            this.setTitle("Gerenciador de Empresas");
        }
    }//GEN-LAST:event_fecharButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        // TODO add your handling code here:
        int resposta = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja sair? Arquivos não salvos seram perdidos.", "Sair do programa", JOptionPane.OK_CANCEL_OPTION);
        if(resposta==0){
            System.exit(0);
        }
    }//GEN-LAST:event_sairButtonActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(arquivoAtual);
        fileChooser.setSelectedFile(arquivoAtual);
        int result = fileChooser.showSaveDialog(jMenu1);
        if (result == JFileChooser.APPROVE_OPTION) {
            arquivoAtual = fileChooser.getSelectedFile();
            // serializa os objetos e salva empresas no arquivo
            for (Empresa empresa : empresaLista) {
                try {
                    empresa.Salvar(arquivoAtual);
                } catch (IOException ex) {
                    Logger.getLogger(InterfaceGrafica.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Erro ao salvar o arquivo: " + ex.getMessage(), "ERRO", JOptionPane.WARNING_MESSAGE);
                } catch (Exception ex) {
                    Logger.getLogger(InterfaceGrafica.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }//GEN-LAST:event_salvarButtonActionPerformed

    private void abrirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirButtonActionPerformed
        // TODO add your handling code here:
        if (!empresaLista.isEmpty()) {
            if (JOptionPane.NO_OPTION == JOptionPane.showConfirmDialog(this, "Já existem empresas. Deseja sobrescrevê-las?", "Abrir Empresas", JOptionPane.YES_NO_OPTION)) {
                return;
            }
        }
        // use JFileChooser (seção 15.6) para permitir que o usuário abra um arquivo com empresas gravadas nele 
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            arquivoAtual = fileChooser.getSelectedFile();
            //boolean acabou = false;
            empresaLista.clear();
            //while (!acabou) {
                try {
                    empresaAtual = Empresa.Ler(arquivoAtual);
                    this.empresaLista.add(empresaAtual);
                    ArquivoNovoEnable();
                    EmpresaNovaEnable();
                    EditEmpresa.setEnabled(true);
                } catch (IOException ex) {
                    Logger.getLogger(InterfaceGrafica.class.getName()).log(Level.SEVERE, null, ex);
                    //acabou = true;
                }
            }
        //}
    }//GEN-LAST:event_abrirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                InterfaceGrafica interfaceGrafica = new InterfaceGrafica();
                interfaceGrafica.pack();
                interfaceGrafica.setLocationRelativeTo(null);
                interfaceGrafica.setVisible(true);
                
            }
            
        });
    }
    private File arquivoAtual;
    private final ArrayList<Empresa> empresaLista = new ArrayList<>();
    private Empresa empresaAtual;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ColaboradoresButton;
    private javax.swing.JMenuItem EditEmpresa;
    private javax.swing.JMenu EmpresaButton;
    private javax.swing.JMenuItem NewEmpresa;
    private javax.swing.JMenu SetorButton;
    private javax.swing.JMenuItem abrirButton;
    private javax.swing.JMenuItem empresaListar;
    private javax.swing.JMenuItem fecharButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JCheckBoxMenuItem newCliente;
    private javax.swing.JCheckBoxMenuItem newFuncionario;
    private javax.swing.JCheckBoxMenuItem newSetor;
    private javax.swing.JMenuItem novoButton;
    private javax.swing.JMenuItem sairButton;
    private javax.swing.JMenuItem salvarButton;
    // End of variables declaration//GEN-END:variables
}
