/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package empresa;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Lucas
 */
public class NovaEmpresaInterface extends javax.swing.JDialog {
    
    /**
     * Creates new dialog EmpresaInterface
     */
    public NovaEmpresaInterface(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        for (AreaDeAtividade area : AreaDeAtividade.values()) {
            areaCombo.addItem(area.toString());
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        NomeEmpresa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NomeText = new javax.swing.JTextField();
        CnpjEmpresa = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        Ok = new javax.swing.JButton();
        areaCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cnpjText = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        enderecoText = new javax.swing.JTextField();
        pontinhos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrador de empresas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(60, 60));
        jScrollPane2.setViewportView(jTree2);

        NomeEmpresa.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("REGISTRE SUA EMPRESA");

        NomeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeTextActionPerformed(evt);
            }
        });

        CnpjEmpresa.setText("CNPJ:");

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Ok.setText("Ok");
        Ok.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                OkFocusGained(evt);
            }
        });
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });

        areaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saúde", "Indústria", "Comércio", "Finanças", "Tecnologia", "Transporte", "Entretenimento" }));
        areaCombo.setSelectedIndex(-1);
        areaCombo.setSelectedItem(null);
        areaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaComboActionPerformed(evt);
            }
        });

        jLabel1.setText("Area de Atividade:");

        try {
            cnpjText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cnpjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Endereço:");

        enderecoText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        enderecoText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        enderecoText.setEnabled(false);
        enderecoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoTextActionPerformed(evt);
            }
        });

        pontinhos.setText("jButton1");
        pontinhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontinhosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Ok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cancel)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeEmpresa)
                            .addComponent(CnpjEmpresa)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NomeText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(areaCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cnpjText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 95, Short.MAX_VALUE)))
                                .addGap(14, 14, 14))
                            .addComponent(enderecoText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pontinhos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(NomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CnpjEmpresa)
                    .addComponent(cnpjText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enderecoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pontinhos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel)
                    .addComponent(Ok))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public Empresa getModalResult() {
        return empresa;
    }

    public void setModel(Empresa empresa) {
        this.empresa = empresa;
        if (empresa != null) {
            NomeText.setText(empresa.getNome());
            cnpjText.setText(empresa.getCnpj());
            areaCombo.setSelectedItem(empresa.getArea().toString());
            
        }
    }
    
    private void NomeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NomeTextActionPerformed

    private void areaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaComboActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_areaComboActionPerformed
    
    

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        // TODO add your handling code here:
        
        try {
            int indexArea = areaCombo.getSelectedIndex();
            empresa = new Empresa(NomeText.getText(), cnpjText.getText(),AreaDeAtividade.values()[indexArea], enderecoEmpresa);
            JOptionPane.showMessageDialog(this, "Empresa registrada com sucesso. \n" + empresa.toString(), "Alerta", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            }
        catch (HeadlessException ex) {
            Logger.getLogger(NovaEmpresaInterface.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Preencha todos os campos");
           }
        catch (Exception ex) {
            Logger.getLogger(NovaEmpresaInterface.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao registrar a empresa: " + ex.getMessage());
            }
        
        
    }//GEN-LAST:event_OkActionPerformed

    public Empresa getEmpresa() {
        return empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    private void OkFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OkFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_OkFocusGained

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Empresa não registrada", "Alerta",JOptionPane.WARNING_MESSAGE);
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void pontinhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontinhosActionPerformed
        // TODO add your handling code here:
        DialogEndereco dialog = new DialogEndereco(null, true);
        if (empresa != null) {
            dialog.setModel(empresa.getEndereco());
        }
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        // a janela de diálogo modal foi escondida
        Endereco retorno = dialog.getModel();
        if (retorno != null) {
            enderecoEmpresa = retorno;
            enderecoText.setText(retorno.toString());
        }
        
    }//GEN-LAST:event_pontinhosActionPerformed

    private void cnpjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpjTextActionPerformed

    private void enderecoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoTextActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaEmpresaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaEmpresaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaEmpresaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaEmpresaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                NovaEmpresaInterface dialog = new NovaEmpresaInterface(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private Endereco enderecoEmpresa;
    private Empresa empresa;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel CnpjEmpresa;
    private javax.swing.JLabel NomeEmpresa;
    private javax.swing.JTextField NomeText;
    private javax.swing.JButton Ok;
    private javax.swing.JComboBox<String> areaCombo;
    private javax.swing.JFormattedTextField cnpjText;
    private javax.swing.JTextField enderecoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree2;
    private javax.swing.JButton pontinhos;
    // End of variables declaration//GEN-END:variables
}
